export const SUBMIT_ERROR_MODAL_SHOW = "SUBMIT_ERROR_MODAL_SHOW";
export const SUBMIT_ERROR_MODAL_CLOSE = "SUBMIT_ERROR_MODAL_CLOSE";

export const CONFIRM_SUBMIT_MODAL_SHOW = "CONFIRM_SUBMIT_MODAL_SHOW";
export const CONFIRM_SUBMIT_MODAL_CLOSE = "CONFIRM_SUBMIT_MODAL_CLOSE";

export const SHOW_CONFIRMATION_MODAL = "SHOW_CONFIRMATION_MODAL";
export const CLOSE_CONFIRMATION_MODAL = "CLOSE_CONFIRMATION_MODAL";

export const SET_PROMPT_NEXT_LOACATION = "SET_PROMPT_NEXT_LOACATION";
export const CLEAR_PROMPT_NEXT_LOACATION = "CLEAR_PROMPT_NEXT_LOACATION";
