export const SHOW_CHANNELS = "SHOW_CHANNELS";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const DELETE_CHANNEL = "CHANNEL_DELETE";
export const ADD_TO_CHANNEL = "ADD_TO_CHANNEL";
export const REMOVE_FROM_CHANNEL = "REMOVE_FROM_CHANNEL";
